---
# tasks file for automsyqlbackup

- name: include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: include os specific tasks
  include_tasks: "setup-{{ ansible_os_family }}.yml"
